swagger: "2.0"
info:
  description: "This is a simple CRUD API for managing notes."
  version: "1.0.0"
  title: "ToDo App API"
host: "http://127.0.0.1:5000/"
basePath: "/"
schemes:
  - "http"
paths:
  /getNotes:
    get:
      summary: "Get all notes"
      description: "Returns a list of all notes"
      produces:
        - "application/json"
      responses:
        200:
          description: "A list of notes"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Note"
  /addNotes:
    post:
      summary: "Add a new note"
      description: "Creates a new note"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          newNote: "Note object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Note"
      responses:
        201:
          description: "Added Successfully"
        500:
          description: "Failed to add the note"
  /deleteNotes:
    delete:
      summary: "Delete a note"
      description: "Deletes a note by ID"
      parameters:
        - in: "query"
          name: "id"
          type: "string"
          required: true
          description: "ID of the note to be deleted"
      responses:
        200:
          description: "Deleted Successfully"
        404:
          description: "Note not found"
definitions:
  Note:
    type: "object"
    properties:
      id:
        type: "string"
      description:
        type: "string"
